variables:
  SITE_URL: support.torproject.org
  TRANSLATION_BRANCH: "support-portal"

include:
  - project: tpo/tpa/ci-templates
    file: lektor.yml
  - project: tpo/tpa/ci-templates
    file: static-shim-deploy.yml
